/* Sightline service worker — generated by build/make_site.py. Do not hand-edit. */
const VERSION = 'bce27bb0a630';
const CACHE = 'sightline-' + VERSION;
const SHELL = ['./', 'index.html', 'manifest.json', 'icon-192.png', 'icon-512.png',
               'icon-maskable-512.png', 'favicon-32.png'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request).catch(() => {
      /* Offline and not in the cache: a navigation still gets the app shell. */
      return e.request.mode === 'navigate' ? caches.match('index.html') : Response.error();
    }))
  );
});
